export const poolDb = [
  {
    lptoken: "N2DR",
    rwdtoken: "N2DR",
    lplogo: "tokenlogo.png",
    rwlogo: "tokenlogo.png",
    autocompclass: "btn btn-md btn-success",
    autocompound: "Auto Compound",
  },
  {
    lptoken: "USDT",
    rwdtoken: "N2DR",
    lplogo: "usdt.png",
    rwlogo: "tokenlogo.png",
    autocompclass: "btn btn-md btn-success disabled",
    autocompound: "Auto Compound Unavailable",
  },
  {
    lptoken: "ETH",
    rwdtoken: "N2DR",
    lplogo: "eth.png",
    rwlogo: "tokenlogo.png",
    autocompclass: "btn btn-md btn-success disabled",
    autocompound: "Auto Compound Unavailable",
  },
  {
    lptoken: "MATIC",
    rwdtoken: "N2DR",
    lplogo: "polygon.png",
    rwlogo: "tokenlogo.png",
    autocompclass: "btn btn-md btn-success disabled",
    autocompound: "Auto Compound Unavailable",
  },
  {
    lptoken: "USDT",
    rwdtoken: "N2DR",
    lplogo: "usdt.png",
    rwlogo: "tokenlogo.png",
    autocompclass: "btn btn-md btn-success disabled",
    autocompound: "Auto Compound Unavailable",
  },
  {
    lptoken: "USDC",
    rwdtoken: "N2DR",
    lplogo: "usdc.png",
    rwlogo: "tokenlogo.png",
    autocompclass: "btn btn-md btn-success disabled",
    autocompound: "Auto Compound Unavailable",
  },
];
