import Head from "next/head";
import React, { useEffect, useState } from "react";
import { poolDb } from "../components/poolsdb";
import {
  getPoolDetails,
  action,
  autoCompound,
  mintToken,
} from "../components/config";

const usdcAddr = "0x7aacCC73423861DFBA095e0b61F1Eb3c761aE314";
const usdTAddr = "0xA6939AD4BB341F4b0bA5AeD949E74523Ae7152eb";
const maticAddr = "0x13A7F1B74f027395DeEEDf6481D785CCF5d80e19";
const ethAddr = "0x57Ce8C9e4CB6C55212f28e66236274ae6695A0b0";

export default function Farms() {
  const [poolArray, getPoolArray] = useState([]);
  const [loadingState, setLoadingState] = useState(false);

  useEffect(() => {
    getPoolInfo();
  }, []);

  const getPoolInfo = async () => {
    setInterval(async () => {
      let poolArray = await getPoolDetails();
      getPoolArray(poolArray);
    }, 5000);
  };

  useEffect(() => {
    if (poolArray[0] != undefined) {
      setLoadingState(true);
    }
  }, [poolArray]);

  const showModal = (i) => {
    const { Modal } = require("bootstrap");
    const myModal = new Modal("#autorunmodal" + i);
    myModal.show();
  };

  const stakeTokens = async (i, tokenAddress) => {
    let amount = document.getElementById("amt" + i).value;
    let result = await action(i, amount, tokenAddress, "stake");
    if (result == true) {
      let output = "Stake Completed!";
      document.getElementById("result").innerHTML = output;
    }
  };

  const unstakeTokens = async (i, tokenAddress) => {
    let amount = document.getElementById("amt" + i).value;
    let result = await action(i, amount, tokenAddress, "unstake");
    if (result == true) {
      let output = "Unstake Completed!";
      document.getElementById("result").innerHTML = output;
    }
  };

  if (loadingState == false)
    return (
      <div className="backstyle" style={{ fontFamily: "SF Pro Display" }}>
        <Head>
          <title>ShreyDeX</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container">
          <div className="my-4 mx-5 rounded shadow-sm">
            <h3 className="my-10">
              DeFI Staking Pools-(Consider staking your claim by minting a new
              token for yourself)
            </h3>
            <video autoPlay muted loop playsInline>
              <source
                className="rounded d-flex align-items-center  "
                type="video/webm"
                src="bannervid.webm"
                width="1400px"
                height="500px"
              />
            </video>
          </div>
          <h5>Fetching Details</h5>
        </main>
      </div>
    );
  return (
    <div className="container" style={{ fontFamily: "SF Pro Display" }}>
      <div className="col-lg-10 my-2 mx-auto rounded shadow-sm">
        <h3 className="mx-auto my-10">
          DeFI Staking Pools- (Consider staking your claim by minting a new
          token for yourself)
        </h3>
        <div
          className="d-flex align-items-center col-lg-10 mx-auto p-2 pb-1 mb-1 text-white rounded shadow-sm"
          style={{ backgroundColor: "#00000060" }}
        >
          <div className="d-grid col-2 ">
            <h6>USDT-LP :-</h6>
            <h5
              style={{ color: "#02D8E9", textShadow: "0px 0px 2px #ffffff90" }}
            >
              <button
                type="button"
                onClick={() => mintToken(usdTAddr)}
                className="btn btn-md stakestyle"
              >
                MINT USDT
              </button>
            </h5>
          </div>
          <div className="d-grid col-2">
            <h6>USDC-LP :-</h6>
            <h5 style={{ color: "#39FF14" }}>
              <button
                type="button"
                className="btn btn-md stakestyle"
                onClick={() => mintToken(usdcAddr)}
              >
                MINT USDC
              </button>
            </h5>
          </div>
          <div className="d-grid col-2">
            <h6>ETH-LP :-</h6>
            <h5 style={{ color: "#39FF14" }}>
              <button
                type="button"
                onClick={() => mintToken(ethAddr)}
                className="btn btn-md stakestyle"
              >
                MINT ETH
              </button>
            </h5>
          </div>
          <div className="d-grid col-2">
            <h6 className="text-justify">MATIC-LP :-</h6>
            <h5 style={{ color: "#39FF14" }}>
              <button
                type="button"
                className="btn btn-md stakestyle"
                onClick={() => mintToken(maticAddr)}
              >
                MINT MATIC
              </button>
            </h5>
          </div>
        </div>
        <video autoPlay muted loop playsInline>
          <source
            className="rounded d-flex justify-content-center"
            type="video/webm"
            src="bannervid.webm"
            width="1500px"
          />
        </video>
      </div>
      {poolDb.map((data, i) => (
        <div
          key={i}
          className="d-flex align-items-center col-lg-10 mx-auto p-2 pb-1 mb-1 text-white rounded shadow-sm"
          style={{ backgroundColor: "#00000060" }}
        >
          <div className="d-grid col-3 mx-5">
            <h6>
              Stake {data.lptoken}/{data.rwdtoken} LP's, Earn {data.rwdtoken}{" "}
            </h6>
            <h3 className="text-white">
              <img src={data.lplogo} width={70} />/
              <img src={data.rwlogo} width={70} />
            </h3>
            <small></small>
          </div>
          <div className="d-grid col-2">
            <h6>Flex APY</h6>
            <h5>{poolArray[i].apy}%</h5>
          </div>
          <div className="d-grid col-2 ">
            <h6>My Stakings</h6>
            <h5
              style={{ color: "#02D8E9", textShadow: "0px 0px 2px #ffffff90" }}
            >
              {poolArray[i].userstaked}
            </h5>
          </div>
          <div className="d-grid col-2">
            <h6>Pending Rewards</h6>
            <h5 style={{ color: "#39FF14" }}>{poolArray[i].reward}</h5>
          </div>
          <div className="d-grid col-2 mx-1">
            <h6>Total Staked In Pool</h6>
            <h5>{poolArray[i].totalstaked}</h5>
          </div>
          <div className="d-grid col">
            <button
              type="button"
              className="btn btn-md stakestyle"
              onClick={() => showModal(i)}
            >
              Open Pool
            </button>
            <div id={"autorunmodal" + i} className="modal fade" role="dialog">
              <div className="modal-dialog modal-dialog-centered">
                <div
                  className="modal-content"
                  style={{ background: "#05014a" }}
                >
                  <div className="modal-header">
                    <h4 className="modal-title">
                      Stake <img src={data.lplogo} width={70} />/
                      <img src={data.rwlogo} width={70} />
                    </h4>
                    <div id="result" />
                  </div>
                  <div className="modal-body mx-auto col-10">
                    <div className="d-grid mx-auto col-10">
                      <input
                        style={{ background: "#ffffff40", color: "white" }}
                        className="form-control"
                        type="text"
                        id={"amt" + i}
                        placeholder="Input Amount: Ex: 3231.19"
                      ></input>
                    </div>
                    <div className="row pb-2" style={{ fontWeight: "800" }}>
                      <div className="d-grid mx-auto col-4 mt-2">
                        <button
                          onClick={() => stakeTokens(i, poolArray[i].tokenaddr)}
                          className="btn btn-dark"
                        >
                          STAKE
                        </button>
                      </div>
                      <div className="d-grid mx-auto col-4 mt-2">
                        <button
                          onClick={() =>
                            unstakeTokens(i, poolArray[i].tokenaddr)
                          }
                          className="btn btn-dark"
                        >
                          UNSTAKE
                        </button>
                      </div>
                    </div>
                    <div className="d-grid mx-auto col-6">
                      <button
                        onClick={autoCompound}
                        className={data.autocompclass}
                      >
                        {data.autocompound}
                      </button>
                    </div>
                  </div>
                  <div className="modal-footer">
                    <div className="d-grid col">
                      <h6>Your Stakings</h6>
                      <h5
                        style={{
                          color: "#02D8E9",
                          textShadow: "0px 0px 2px #ffffff90",
                        }}
                      >
                        {poolArray[i].userstaked}
                      </h5>
                    </div>
                    <div className="d-grid col">
                      <h6>Your Earnings</h6>
                      <h5
                        style={{
                          color: "#39FF14",
                          textShadow: "0px 0px 2px #ffffff90",
                        }}
                      >
                        {poolArray[i].reward}
                      </h5>
                    </div>
                    <div className="d-grid col">
                      <h6>Multiplier</h6>
                      <h4
                        style={{
                          color: "red",
                          textShadow: "0px 0px 1px #ffffff",
                        }}
                      >
                        x{poolArray[i].multiplier}
                      </h4>
                    </div>
                    <div className="d-grid col">
                      <h6>In Your Wallet</h6>
                      <h5
                        style={{
                          color: "white",
                          textShadow: "0px 0px 1px #ffffff",
                        }}
                      >
                        {poolArray[i].userbalance}
                      </h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
